### ISSUE TITLE
Rants button gone/extension not working 8/14/2024

### ISSUE THREAD

**Issue by MLChristiansen** [rantstats/rantstats-extension#16]
Have used the extension twice weekly for years - as of 8/14/2024, the extension's rants button is no longer appearing in the chat.  Hope it can be fixed - the extension is very useful!

**Comment by stevencrader** [comment]
Thanks. I heard about it for the first time while listening to a recording of a show from last night.

I'm away from a computer until Saturday. I'll submit a fix for it then. It usually takes Google a couple days to approve after that.

**Comment by stevencrader** [comment]
I've submitted a new version for approval.

**Comment by MLChristiansen** [comment]
Thanks - I very much appreciate your quick work on this.  Unfortunately, it's still not working for me.  I tried uninstalling and reinstalling, no change.  Tried in both Brave and Chrome browsers.  Did I miss something?

**Comment by stevencrader** [comment]
It hasn't been approved yet. It usually takes Google a couple days to approve it before you will receive the new version.

**Comment by MLChristiansen** [comment]
Oh I see - thank you for clarifying and for your quick work.  Again, if there are ways I can send you a tip, please let me know.  Your extension is very valuable and it's crazy that Rumble still has not implemented a way to track Rants easily.

**Comment by stevencrader** [comment]
Thank you. I'll post here when Google approves it. 

If you feel inclined, you can send a tip to me using [PayPal](https://www.paypal.com/paypalme/stevencrader) or [Bitcoin/Lightning](https://getalby.com/p/stevencrader). No tip is necessary though.

I'm also surprised Rumble hasn't implemented something yet either.

**Comment by stevencrader** [comment]
The update has been released to the Chrome store. You should receive the update automatically.

**Comment by stevencrader** [comment]
Thank you for your generous support!

**Comment by MLChristiansen** [comment]
Yep looks to be working now - thank you, and you are most welcome.
